FROM node:20-alpine AS base
WORKDIR /app

RUN apk add --no-cache openssl busybox-extras

COPY package*.json ./
RUN npm ci --omit=dev

COPY prisma ./prisma
RUN npx prisma generate

COPY src ./src
COPY docker-entrypoint.sh ./docker-entrypoint.sh

EXPOSE 4000
CMD ["./docker-entrypoint.sh"]
